# This is a basic workflow to help you get started with Actions

name: Terraform Action

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      terraform_action:
        description: "Select Terraform action (Choose 'create' before test execution, 'destroy' after ALL executions are over)"
        required: true
        type: choice
        options:
          - create
          - destroy

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::005057437287:role/aws-gh-oidc

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        id: init
        run: terraform init
    
      - name: Terraform validate
        id: validate
        run: terraform validate
 
      - name: Terraform plan
        if: ${{ inputs.terraform_action == 'create' }}
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
 
      - name: Terraform Apply
        if: ${{ inputs.terraform_action == 'create' }}
        run: terraform apply -auto-approve -input=false

      - name: Terraform destroy
        if: ${{ inputs.terraform_action == 'destroy' }}
        id: destroy
        run: terraform destroy -auto-approve
